// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrca-1BOtiZQkuNN3lTR7U3J9hZYWXjCM',
    appId: '1:302554772027:web:9ef89a6edb6a3a1ff0e21e',
    messagingSenderId: '302554772027',
    projectId: 'list-tiles-fbproject',
    authDomain: 'list-tiles-fbproject.firebaseapp.com',
    storageBucket: 'list-tiles-fbproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz-WIfVyFUYQ2uNf9-2zGYRRsmTe4tLjI',
    appId: '1:302554772027:android:4c0bc7feb2e0fc64f0e21e',
    messagingSenderId: '302554772027',
    projectId: 'list-tiles-fbproject',
    storageBucket: 'list-tiles-fbproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxI3P6zCwUr2xAuhsheDJ4TT_1aDciLb4',
    appId: '1:302554772027:ios:2c6d2006d38f51c5f0e21e',
    messagingSenderId: '302554772027',
    projectId: 'list-tiles-fbproject',
    storageBucket: 'list-tiles-fbproject.appspot.com',
    iosClientId: '302554772027-g8pd41c2aqt7grm4f3rbh40gm7v7p7jt.apps.googleusercontent.com',
    iosBundleId: 'com.example.listTiles',
  );
}
